# Generated by Django 5.0.6 on 2024-09-16 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_contentcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentrequest',
            name='category',
            field=models.CharField(choices=[('project', 'Project'), ('meetup', 'Meetup'), ('knowledge', 'Knowledge'), ('achievement', 'Achievement'), ('research', 'Research'), ('bug', 'Bug')], max_length=20),
        ),
        migrations.RemoveField(
            model_name='generatedcontent',
            name='content_request',
        ),
        migrations.RemoveField(
            model_name='generatedcontent',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='contentrequest',
            name='platforms',
        ),
        migrations.AddField(
            model_name='contentrequest',
            name='word_count',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='contentrequest',
            name='writing_style',
            field=models.CharField(choices=[('formal', 'Formal'), ('casual', 'Casual'), ('technical', 'Technical'), ('storytelling', 'Storytelling')], default='casual', max_length=20),
        ),
        migrations.DeleteModel(
            name='ContentCategory',
        ),
        migrations.DeleteModel(
            name='GeneratedContent',
        ),
        migrations.DeleteModel(
            name='Platform',
        ),
        migrations.AddField(
            model_name='contentrequest',
            name='platforms',
            field=models.CharField(default='linkedin', max_length=100),
        ),
    ]
