# Generated by Django 5.0.6 on 2024-09-21 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_contentrequest_category_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContentRequest',
        ),
    ]
